In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2 , np.nan,4],
    "B": [ 5.1, np.nan,6.6,8.8],
    "C": ["foo","zoo","bar", np.nan],
    'D':[6,7,8,9]
})
print(df)

In [ ]:
df.dropna(axis=1)

In [ ]:
df.fillna(0)

In [ ]:
df.ffill(axis=0)

In [ ]:
df.bfill()

In [18]:
df2=pd.read_csv('/Users/algo trading 2026/batch 38/10_numpy_pandas/unicorn.csv')
df2

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
0,Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,NaN
1,SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7.0
2,SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
3,Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2.0
4,Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...,...
1069,Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
1070,Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
1071,Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80.0
1072,Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0
1073,Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [31]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company       1074 non-null   str
 1   Valuation     1074 non-null   int64
 2   Date Joined   1074 non-null   str
 3   Industry      1074 non-null   str
 4   City          1074 non-null   object
 5   Country       1074 non-null   str
 6   Continent     1074 non-null   str
 7   Year Founded  1074 non-null   int64
 8   Funding       1074 non-null   int64
dtypes: int64(3), object(1), str(5)
memory usage: 75.6+ KB

In [32]:
df2

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
0,Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,1
1,SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7
2,SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2
3,Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2
4,Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4
...,...,...,...,...,...,...,...,...,...
1069,Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379
1070,Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990
1071,Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80
1072,Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792
1073,Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620

In [21]:
df2=df2.fillna(1)

In [30]:
df2['Funding'] = df2['Funding'].astype(int)

In [16]:
df=pd.read_csv('sp500_companies.csv')
df

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    str
 1   Security               503 non-null    str
 2   GICS Sector            503 non-null    str
 3   GICS Sub-Industry      503 non-null    str
 4   Headquarters Location  503 non-null    str
 5   Date added             503 non-null    str
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    str
dtypes: int64(1), str(7)
memory usage: 31.6 KB