In [ ]:
import numpy as np
np1=np.arange(100,125).reshape(5,5)
print(np1)

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]

In [2]:
!pip install pandas

Collecting pandas
  Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=2.3.3 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.5

In [1]:
import pandas as pd
df1=pd.DataFrame(np1,index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4','col5'])
print(df1)

NameError: name 'np1' is not defined

In [10]:
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]
pd2=pd.DataFrame(l1, columns=['col1','col2','col3','col4','col5'],index=['r1','r2','r3','r4','r5'])
pd2

    col1  col2  col3  col4  col5
r1     1     2     3     4     5
r2     6     7     8     9    10
r3    11    12    13    14    15
r4    16    17    18    19    20
r5    21    22    23    24    25

In [11]:
ld1={'tech':['amzn','msft','aapl','googl','tsla']
     ,'pharma':['pfizer','moderna','astrazeneca','novavax','johnson']
     ,'auto':['tesla','toyota','honda','ford','bmw']
     ,'finance':['jpmorgan','goldman','citi','wellsfargo','bankofamerica']
     }
pd3=pd.DataFrame(ld1)
pd3

    tech       pharma    auto        finance
0   amzn       pfizer   tesla       jpmorgan
1   msft      moderna  toyota        goldman
2   aapl  astrazeneca   honda           citi
3  googl      novavax    ford     wellsfargo
4   tsla      johnson     bmw  bankofamerica

In [14]:
l1=[{'Name':'Alice','Age':25,'City':'New York'},
    {'Name':'Bob','Age':30,'City':'Los Angeles'},
    {'Name':'Charlie','Age':35,'City':'Chicago'}]
df4=pd.DataFrame(l1)
df4

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
pd.read_exl()

In [3]:
pd.read_csv('/Users/algo trading 2026/batch 38/10_numpy_pandas/sp500.csv')

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [ ]:
pd.read_html()