In [2]:
import numpy as np
np1=np.arange(100,125).reshape(5,5)
print(np1)

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]

In [2]:
!pip install pandas

Collecting pandas
  Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=2.3.3 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.5

In [3]:
import pandas as pd
df1=pd.DataFrame(np1,index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4','col5'])
print(df1)

      col1  col2  col3  col4  col5
row1   100   101   102   103   104
row2   105   106   107   108   109
row3   110   111   112   113   114
row4   115   116   117   118   119
row5   120   121   122   123   124

In [10]:
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]
pd2=pd.DataFrame(l1, columns=['col1','col2','col3','col4','col5'],index=['r1','r2','r3','r4','r5'])
pd2

    col1  col2  col3  col4  col5
r1     1     2     3     4     5
r2     6     7     8     9    10
r3    11    12    13    14    15
r4    16    17    18    19    20
r5    21    22    23    24    25

In [11]:
ld1={'tech':['amzn','msft','aapl','googl','tsla']
     ,'pharma':['pfizer','moderna','astrazeneca','novavax','johnson']
     ,'auto':['tesla','toyota','honda','ford','bmw']
     ,'finance':['jpmorgan','goldman','citi','wellsfargo','bankofamerica']
     }
pd3=pd.DataFrame(ld1)
pd3

    tech       pharma    auto        finance
0   amzn       pfizer   tesla       jpmorgan
1   msft      moderna  toyota        goldman
2   aapl  astrazeneca   honda           citi
3  googl      novavax    ford     wellsfargo
4   tsla      johnson     bmw  bankofamerica

In [14]:
l1=[{'Name':'Alice','Age':25,'City':'New York'},
    {'Name':'Bob','Age':30,'City':'Los Angeles'},
    {'Name':'Charlie','Age':35,'City':'Chicago'}]
df4=pd.DataFrame(l1)
df4

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [8]:
pd.read_excel(r'/Users/algo trading 2026/batch 38/10_numpy_pandas/e500 (2).xlsx')

,Unnamed: 0,Name,Sector,Price,EPS
0,0,Apple Inc,Information Technology,170.12,9.20
1,1,Abbvie Inc,Health Care,93.29,5.31
2,2,Abbott Laboratories,Health Care,55.28,2.41
3,3,Accenture Plc,Information Technology,145.30,NaN
4,4,Allergan Plc,Health Care,171.81,15.42
...,...,...,...,...,...
97,97,Verizon Communications Inc,Telecommunications,45.85,3.75
98,98,Walgreens Boots Alliance,Consumer Staples,70.25,5.10
99,99,Wells Fargo & Company,Financials,54.02,4.14
100,100,Wal-Mart Stores,Consumer Staples,96.08,4.36
101,101,Exxon Mobil Corp,Energy,80.31,3.56

In [7]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [4]:
df10=pd.read_csv(r'/Users/algo trading 2026/batch 38/10_numpy_pandas/sp500.csv')

In [10]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.2-cp314-cp314-macosx_10_15_universal2.whl.metadata (3.3 kB)
Downloading lxml-6.1.2-cp314-cp314-macosx_10_15_universal2.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 13.9 MB/s  0:00:00 eta 0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.1.2

In [16]:
pd.read_html('https://www.screener.in/screens/281185/nifty-50/')[0]

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1316.00,23.83,1780881.61,0.46,23196.00,2.02,309468.00,27.02,10.26
1,2.,Bharti Airtel,1946.00,38.88,1214401.51,1.23,10011.60,40.84,58539.10,18.35,17.56
2,3.,HDFC Bank,726.95,14.18,1120311.43,1.79,20382.69,18.37,90575.33,3.67,7.02
3,4.,ICICI Bank,1420.00,18.17,1019048.09,0.85,16276.22,13.88,52240.85,6.44,7.18
4,5.,SBI,1048.70,11.52,968014.87,1.65,25120.89,13.73,136240.49,8.36,6.13
5,6.,TCS,2302.00,15.51,832883.75,2.78,13420.00,8.45,72275.00,13.93,63.03
6,7.,Bajaj Finance,1095.00,33.29,681742.00,0.49,6080.60,27.37,23165.45,18.65,10.87
7,8.,Larsen & Toubro,4093.00,31.96,563141.99,0.93,4988.03,13.98,67941.74,6.69,14.57
8,9.,Life Insurance,422.25,8.89,534146.06,2.37,13584.25,23.98,239865.70,6.76,35.14
9,10.,Hind. Unilever,2015.00,42.93,473442.64,2.03,2680.00,-3.72,17341.00,10.05,28.42
10,11.,Sun Pharma.Inds.,1902.40,36.13,456449.48,0.84,2901.23,5.95,15299.88,10.46,20.53
11,12.,Infosys,1121.00,14.59,454908.14,4.28,7775.00,12.25,48211.00,14.03,39.95
12,13.,Titan Company,5086.10,77.37,451536.92,0.29,1777.00,62.88,21356.00,29.25,20.54
13,14.,Maruti Suzuki,13565.00,29.75,426487.09,1.03,3446.90,-9.11,52469.80,35.91,18.87
14,15.,M & M,3412.20,22.13,424316.91,0.97,5997.56,33.80,58187.57,27.80,15.10
15,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
16,16.,Adani Enterp.,2997.00,170.86,405622.85,0.04,-1461.54,-35.82,32923.98,49.92,5.80
17,17.,Kotak Mah. Bank,402.80,20.01,400691.58,0.16,5480.46,22.55,18354.57,6.41,6.98
18,18.,Adani Power,205.50,27.80,396300.48,0.00,4866.60,41.98,18901.89,33.97,17.22
19,19.,Adani Ports,1700.00,29.48,391673.05,0.44,3649.50,9.23,10820.80,18.57,14.12
20,20.,Axis Bank,1245.80,13.96,387805.76,0.08,7670.37,22.24,35541.96,9.87,6.24
21,21.,HCL Technologies,1302.50,19.50,353454.88,4.15,4626.00,20.32,34579.00,13.94,30.40
22,22.,UltraTech Cem.,11570.00,39.53,340943.80,2.07,2603.72,15.75,24648.20,15.85,12.66
23,23.,ITC,269.40,17.09,337552.33,5.38,4508.79,-22.00,19114.37,-11.07,38.91
24,24.,Hind.Aeronautics,5000.00,35.87,334387.50,0.90,1589.66,14.88,5515.17,14.45,31.97
25,25.,NTPC,340.00,11.88,329686.65,2.65,6896.44,11.82,50740.96,7.81,8.92

In [ ]:
import requests, re, pandas as pd

s = requests.Session()
url = "https://chartink.com/screener/nifty-50-stocks"
h = {"User-Agent": "Mozilla/5.0"}

page = s.get(url, headers=h, timeout=30)
csrf = re.search(r'name="csrf-token" content="([^"]+)"', page.text).group(1)

h |= {"x-csrf-token": csrf, "x-requested-with": "XMLHttpRequest", "referer": url}
resp = s.post("https://chartink.com/screener/process",
              headers=h,
              data={"scan_clause": "( {33489} ( latest close > 0 ) )"},
              timeout=30)

df = pd.DataFrame(resp.json()["data"])
df
#request,selelium,playwright,beautifulsoup,requests,seleniumwire,undetected_chromedriver,pyppeteer,pyppeteer_stealth
#antigravity

,sr,nsecode,name,bsecode,close,per_chg,volume
0,1,BANKNIFTY,BANKNIFTY,NaN,57761.95,0.46,0
1,2,BOSCHLTD,Bosch Limited,500530,48200.00,-1.13,30216
2,3,PAGEIND,Page Industries Limited,532827,35480.00,-0.07,18862
3,4,POWERINDIA,Hitachi Energy India Ltd,543187,34190.00,2.03,104122
4,5,SHREECEM,Shree Cements Limited,500387,24280.00,-0.08,15450
...,...,...,...,...,...,...,...
205,206,NHPC,Nhpc Limited,533098,76.15,-0.26,7599544
206,207,INOXWIND,Inox Wind Limited,539083,73.60,-0.41,6096098
207,208,SUZLON,Suzlon Energy Limited,532667,46.71,-0.62,32172432
208,209,YESBANK,Yes Bank Limited,532648,22.80,0.26,33859169
209,210,IDEA,Vodafone Idea Ltd,532822,13.94,-0.64,190569146

In [20]:
df.head(10)

,sr,nsecode,name,bsecode,close,per_chg,volume
0,1,BANKNIFTY,BANKNIFTY,NaN,57761.95,0.46,0
1,2,BOSCHLTD,Bosch Limited,500530,48200.00,-1.13,30216
2,3,PAGEIND,Page Industries Limited,532827,35480.00,-0.07,18862
3,4,POWERINDIA,Hitachi Energy India Ltd,543187,34190.00,2.03,104122
4,5,SHREECEM,Shree Cements Limited,500387,24280.00,-0.08,15450
5,6,NIFTY,NIFTY,NaN,24252.00,0.08,0
6,7,SOLARINDS,Solar Industries India Limited,532725,19900.00,0.71,89559
7,8,FORCEMOT,Force Motors Ltd,500033,17770.00,-0.64,40914
8,9,DIXON,Dixon Technologies Ltd,540699,14850.00,0.00,582929
9,10,MARUTI,Maruti Suzuki India Limited,532500,13565.00,-1.77,224951

In [21]:
df.tail(10)

,sr,nsecode,name,bsecode,close,per_chg,volume
200,201,GMRAIRPORT,GMR Airports Ltd,532754,99.63,-0.78,9125448
201,202,NBCC,Nbcc (india) Limited,534309,88.88,0.71,5375979
202,203,IDFCFIRSTB,IDFC First Bank Ltd,539437,86.75,1.06,12594633
203,204,IRFC,Indian Railway Finance Corporation Ltd,543257,86.40,-0.08,4768042
204,205,NMDC,Nmdc Limited,526371,84.61,0.79,18876961
205,206,NHPC,Nhpc Limited,533098,76.15,-0.26,7599544
206,207,INOXWIND,Inox Wind Limited,539083,73.60,-0.41,6096098
207,208,SUZLON,Suzlon Energy Limited,532667,46.71,-0.62,32172432
208,209,YESBANK,Yes Bank Limited,532648,22.80,0.26,33859169
209,210,IDEA,Vodafone Idea Ltd,532822,13.94,-0.64,190569146

In [ ]:
df.info() #nan None

<class 'pandas.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   sr       210 non-null    int64
 1   nsecode  210 non-null    str
 2   name     210 non-null    str
 3   bsecode  205 non-null    str
 4   close    210 non-null    float64
 5   per_chg  210 non-null    float64
 6   volume   210 non-null    int64
dtypes: float64(2), int64(2), str(3)
memory usage: 11.6 KB

In [23]:
df.describe()

               sr         close     per_chg        volume
count  210.000000    210.000000  210.000000  2.100000e+02
mean   105.500000   3135.532048    0.107762  4.637056e+06
std     60.765944   6922.629703    1.113495  1.414798e+07
min      1.000000     13.940000   -3.300000  0.000000e+00
25%     53.250000    395.962500   -0.605000  5.107228e+05
50%    105.500000   1238.500000    0.000000  1.318226e+06
75%    157.750000   2538.200000    0.732500  4.619722e+06
max    210.000000  57761.950000    4.100000  1.905691e+08

In [27]:
df.shape

(210, 7)

In [33]:
list(df.columns)

['sr', 'nsecode', 'name', 'bsecode', 'close', 'per_chg', 'volume']

In [34]:
list(df.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209]

subsetting

1 COL-> SERIES 

MORE THAN COL IS CALLED DATAFRAME

In [9]:
df10

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [10]:
df10.EPS

0       9.20
1       5.31
2       2.41
3        NaN
4      15.42
       ...
97      3.75
98      5.10
99      4.14
100     4.36
101     3.56
Name: EPS, Length: 102, dtype: float64

In [11]:
df10['EPS']

0       9.20
1       5.31
2       2.41
3        NaN
4      15.42
       ...
97      3.75
98      5.10
99      4.14
100     4.36
101     3.56
Name: EPS, Length: 102, dtype: float64

In [12]:
df10[['EPS','Price']]

       EPS   Price
0     9.20  170.12
1     5.31   93.29
2     2.41   55.28
3      NaN  145.30
4    15.42  171.81
..     ...     ...
97    3.75   45.85
98    5.10   70.25
99    4.14   54.02
100   4.36   96.08
101   3.56   80.31

[102 rows x 2 columns]