In [36]:
import pandas as pd
df=pd.read_csv(r'/Users/algo trading 2026/batch 38/10_numpy_pandas/unicorn.csv')
df

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
0,Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,NaN
1,SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7.0
2,SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
3,Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2.0
4,Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...,...
1069,Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
1070,Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
1071,Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80.0
1072,Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0
1073,Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [ ]:
df

In [37]:
df=df.set_index('Company')

In [ ]:
df.set_index('Year Founded',inplace=True)

In [43]:
df2=pd.read_csv('sbin.csv')
df2

                      date    open    high     low   close  volume
0      2019-01-01 09:15:00  297.50  297.70  296.05  296.30  116562
1      2019-01-01 09:16:00  296.30  296.50  296.05  296.35   57789
2      2019-01-01 09:17:00  296.20  296.50  296.10  296.35   42404
3      2019-01-01 09:18:00  296.35  296.35  295.50  295.65   87831
4      2019-01-01 09:19:00  295.70  295.85  295.50  295.60   37799
...                    ...     ...     ...     ...     ...     ...
19995  2019-03-18 11:15:00  296.15  296.45  296.05  296.45   33954
19996  2019-03-18 11:16:00  296.40  296.45  296.00  296.00   37220
19997  2019-03-18 11:17:00  296.00  296.00  295.80  296.00   16007
19998  2019-03-18 11:18:00  296.00  296.00  295.85  295.95   12154
19999  2019-03-18 11:19:00  296.00  296.05  295.65  295.75  118891

[20000 rows x 6 columns]

In [44]:
df2.loc[1,'volume']

np.int64(57789)

In [35]:
df.reset_index(inplace=True)
df

,Year Founded,Company,Valuation,Date Joined,Industry,City,Country,Continent,Funding
0,2012,Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,NaN
1,2002,SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,7.0
2,2008,SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2.0
3,2010,Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2.0
4,2005,Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,4.0
...,...,...,...,...,...,...,...,...,...
1069,2012,Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,379.0
1070,2015,Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,990.0
1071,2018,Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,80.0
1072,2005,Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,792.0
1073,2014,Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,620.0

In [40]:
df

,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
Company,,,,,,,,
Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,NaN
SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7.0
SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2.0
Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...
Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80.0
Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0
Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [48]:
df.loc['Bytedance':'SHEIN','Valuation':'Industry']

           Valuation Date Joined                         Industry
Company
Bytedance        180  07-04-2017          Artificial intelligence
SpaceX           100  01-12-2012                            Other
SHEIN            100  03-07-2018  E-commerce & direct-to-consumer

In [50]:
df.iloc[0:3,0:3]

           Valuation Date Joined                         Industry
Company
Bytedance        180  07-04-2017          Artificial intelligence
SpaceX           100  01-12-2012                            Other
SHEIN            100  03-07-2018  E-commerce & direct-to-consumer

In [42]:
df.loc['Zihaiguo','Funding']

np.float64(80.0)

In [45]:
df.iloc[1,3]

'Hawthorne'

In [46]:
df.loc['Zopa','Year Founded']

np.int64(2005)

In [47]:
df.iloc[-2,-2]

np.int64(2005)