In [2]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-1.7.0-py3-none-any.whl.metadata (6.7 kB)
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Using cached beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.16.3-cp310-abi3-macosx_11_0_arm64.whl.metadata (17 kB)
Requirement already satisfied: lxml>=4.9.0 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from yfinance) (6.1.2)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.16.5 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from yfinance) (2.5.2)
Requirement already satisfied: pandas>=1.3.0 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from yfinance) (3.0.5)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.5.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from yfinance) (4.11.3)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.36.1-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Collecting pytz>=2022.5 (from yfinance)
  Using cached pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests>=2.31 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from yfinance) (2.34.2)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-17.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (6.3 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.11.1->yfinance)
  Downloading soupsieve-2.9.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Collecting cffi>=2.0.0 (from curl_cffi>=0.15->yfinance)
  Downloading cffi-2.1.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.5 kB)
Requirement already satisfied: certifi>=2024.2.2 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Collecting pycparser (from cffi>=2.0.0->curl_cffi>=0.15->yfinance)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/algo trading 2026/batch 38/.venv/lib/python3.14/site-packages (from requests>=2.31->yfinance) (2.7.0)
Downloading yfinance-1.7.0-py3-none-any.whl (149 kB)
Using cached beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading curl_cffi-0.16.3-cp310-abi3-macosx_11_0_arm64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 2.2 MB/s  0:00:01 eta 0:00:01
Downloading cffi-2.1.1-cp314-cp314-macosx_11_0_arm64.whl (184 kB)
Using cached multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.5.1-py3-none-any.whl (193 kB)
Downloading protobuf-7.36.1-cp310-abi3-macosx_10_9_universal2.whl (456 kB)
Using cached pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Downloading soupsieve-2.9.2-py3-none-any.whl (37 kB)
Downloading websockets-17.1-cp314-cp314-macosx_11_0_arm64.whl (214 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: pytz, multitasking, websockets, soupsieve, pycparser, protobuf, peewee, cffi, beautifulsoup4, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/11 [yfinance]/11 [yfinance]soup4]
Successfully installed beautifulsoup4-4.15.0 cffi-2.1.1 curl_cffi-0.16.3 multitasking-0.0.13 peewee-4.5.1 protobuf-7.36.1 pycparser-3.0 pytz-2026.3.post1 soupsieve-2.9.2 websockets-17.1 yfinance-1.7.0

In [10]:
import yfinance as yf
df1=yf.download('TSLA', start='2025-01-01', end='2025-12-31', interval='1h',multi_level_index=False)
df1

[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2025-01-02 09:30:00-05:00,380.336609,391.179993,373.410004,389.689911,42082406
2025-01-02 10:30:00-05:00,382.524994,382.723999,376.250000,380.269989,15683322
2025-01-02 11:30:00-05:00,378.679993,386.149994,378.350006,382.489990,9901739
2025-01-02 12:30:00-05:00,377.709991,379.059998,373.049988,378.675201,12269777
2025-01-02 13:30:00-05:00,377.227295,380.329895,374.869995,377.619995,8053698
...,...,...,...,...,...
2025-12-30 11:30:00-05:00,462.170013,463.119995,460.690002,461.109985,5468641
2025-12-30 12:30:00-05:00,460.496002,462.279999,458.579987,462.130005,4954327
2025-12-30 13:30:00-05:00,458.614990,460.739990,457.880005,460.470001,4209010
2025-12-30 14:30:00-05:00,456.119995,458.709991,456.100006,458.600006,5133024
2025-12-30 15:30:00-05:00,454.429993,456.459991,454.040009,456.140015,3950479

In [11]:
import yfinance as yf
df2=yf.download('RELIANCE.NS', start='2025-01-01', end='2025-12-31', interval='1h',multi_level_index=False)
df2

[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2025-01-01 09:15:00+05:30,1215.500000,1217.900024,1211.599976,1215.849976,0
2025-01-01 10:15:00+05:30,1220.300049,1221.000000,1214.500000,1215.099976,898260
2025-01-01 11:15:00+05:30,1220.300049,1222.550049,1216.599976,1220.349976,631005
2025-01-01 12:15:00+05:30,1222.150024,1226.250000,1220.000000,1220.300049,1347095
2025-01-01 13:15:00+05:30,1224.150024,1225.949951,1221.199951,1222.150024,951098
...,...,...,...,...,...
2025-12-30 11:15:00+05:30,1543.199951,1546.199951,1540.199951,1545.900024,673873
2025-12-30 12:15:00+05:30,1543.500000,1546.900024,1542.400024,1543.000000,906953
2025-12-30 13:15:00+05:30,1543.500000,1546.400024,1542.199951,1543.500000,1142834
2025-12-30 14:15:00+05:30,1539.300049,1545.000000,1538.000000,1543.500000,3090767
2025-12-30 15:15:00+05:30,1540.500000,1542.400024,1538.000000,1539.300049,1246779

In [18]:
tz1='Asia/Kolkata'
tz2='America/New_York'
tz3='UTC'
df1.index = df1.index.tz_convert(tz1)
df1

,Close,High,Low,Open,Volume
Datetime,,,,,
2025-01-02 20:00:00+05:30,380.336609,391.179993,373.410004,389.689911,42082406
2025-01-02 21:00:00+05:30,382.524994,382.723999,376.250000,380.269989,15683322
2025-01-02 22:00:00+05:30,378.679993,386.149994,378.350006,382.489990,9901739
2025-01-02 23:00:00+05:30,377.709991,379.059998,373.049988,378.675201,12269777
2025-01-03 00:00:00+05:30,377.227295,380.329895,374.869995,377.619995,8053698
...,...,...,...,...,...
2025-12-30 22:00:00+05:30,462.170013,463.119995,460.690002,461.109985,5468641
2025-12-30 23:00:00+05:30,460.496002,462.279999,458.579987,462.130005,4954327
2025-12-31 00:00:00+05:30,458.614990,460.739990,457.880005,460.470001,4209010
2025-12-31 01:00:00+05:30,456.119995,458.709991,456.100006,458.600006,5133024
2025-12-31 02:00:00+05:30,454.429993,456.459991,454.040009,456.140015,3950479

In [24]:
d1=df1.reset_index()
d1['Datetime'].dt.tz_convert(tz3)

0      2025-01-02 14:30:00+00:00
1      2025-01-02 15:30:00+00:00
2      2025-01-02 16:30:00+00:00
3      2025-01-02 17:30:00+00:00
4      2025-01-02 18:30:00+00:00
                  ...
1726   2025-12-30 16:30:00+00:00
1727   2025-12-30 17:30:00+00:00
1728   2025-12-30 18:30:00+00:00
1729   2025-12-30 19:30:00+00:00
1730   2025-12-30 20:30:00+00:00
Name: Datetime, Length: 1731, dtype: datetime64[s, UTC]

In [25]:
d1['Datetime'].dt.tz_localize(None)

0      2025-01-02 20:00:00
1      2025-01-02 21:00:00
2      2025-01-02 22:00:00
3      2025-01-02 23:00:00
4      2025-01-03 00:00:00
               ...
1726   2025-12-30 22:00:00
1727   2025-12-30 23:00:00
1728   2025-12-31 00:00:00
1729   2025-12-31 01:00:00
1730   2025-12-31 02:00:00
Name: Datetime, Length: 1731, dtype: datetime64[s]